/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as WorkspaceRouteImport } from "./routes/_workspace";
import { Route as WorkspaceActivityRouteImport } from "./routes/_workspace.activity";
import { Route as WorkspaceAppsRouteImport } from "./routes/_workspace.apps";
import { Route as WorkspaceCallsRouteImport } from "./routes/_workspace.calls";
import { Route as WorkspaceDocumentsRouteImport } from "./routes/_workspace.documents";
import { Route as WorkspaceFilesRouteImport } from "./routes/_workspace.files";
import { Route as WorkspaceHomeRouteImport } from "./routes/_workspace.home";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as SettingsSectionRouteImport } from "./routes/settings.$section";
import { Route as WorkspaceAdminIndexRouteImport } from "./routes/_workspace.admin.index";
import { Route as WorkspaceAdminSectionRouteImport } from "./routes/_workspace.admin.$section";
import { Route as WorkspaceAppsIndexRouteImport } from "./routes/_workspace.apps.index";
import { Route as WorkspaceAppsAppIdRouteImport } from "./routes/_workspace.apps.$appId";
import { Route as WorkspaceChannelsIndexRouteImport } from "./routes/_workspace.channels.index";
import { Route as WorkspaceChannelsChatIdRouteImport } from "./routes/_workspace.channels.$chatId";
import { Route as WorkspaceChatsIndexRouteImport } from "./routes/_workspace.chats.index";
import { Route as WorkspaceChatsChatIdRouteImport } from "./routes/_workspace.chats.$chatId";
import { Route as WorkspaceDocumentsIndexRouteImport } from "./routes/_workspace.documents.index";
import { Route as WorkspaceDocumentsDocumentIdRouteImport } from "./routes/_workspace.documents.$documentId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: "/_workspace",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspaceActivityRoute = WorkspaceActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceAppsRoute = WorkspaceAppsRouteImport.update({
  id: "/apps",
  path: "/apps",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceCallsRoute = WorkspaceCallsRouteImport.update({
  id: "/calls",
  path: "/calls",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceDocumentsRoute = WorkspaceDocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceFilesRoute = WorkspaceFilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceHomeRoute = WorkspaceHomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => WorkspaceRoute,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: "/settings/$section",
  path: "/settings/$section",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspaceAdminIndexRoute = WorkspaceAdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceAdminSectionRoute = WorkspaceAdminSectionRouteImport.update({
  id: "/admin/$section",
  path: "/admin/$section",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceAppsIndexRoute = WorkspaceAppsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspaceAppsRoute,
} as any);
const WorkspaceAppsAppIdRoute = WorkspaceAppsAppIdRouteImport.update({
  id: "/$appId",
  path: "/$appId",
  getParentRoute: () => WorkspaceAppsRoute,
} as any);
const WorkspaceChannelsIndexRoute = WorkspaceChannelsIndexRouteImport.update({
  id: "/channels/",
  path: "/channels/",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceChannelsChatIdRoute = WorkspaceChannelsChatIdRouteImport.update({
  id: "/channels/$chatId",
  path: "/channels/$chatId",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceChatsIndexRoute = WorkspaceChatsIndexRouteImport.update({
  id: "/chats/",
  path: "/chats/",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceChatsChatIdRoute = WorkspaceChatsChatIdRouteImport.update({
  id: "/chats/$chatId",
  path: "/chats/$chatId",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceDocumentsIndexRoute = WorkspaceDocumentsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspaceDocumentsRoute,
} as any);
const WorkspaceDocumentsDocumentIdRoute =
  WorkspaceDocumentsDocumentIdRouteImport.update({
    id: "/$documentId",
    path: "/$documentId",
    getParentRoute: () => WorkspaceDocumentsRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/activity": typeof WorkspaceActivityRoute;
  "/apps": typeof WorkspaceAppsRouteWithChildren;
  "/calls": typeof WorkspaceCallsRoute;
  "/documents": typeof WorkspaceDocumentsRouteWithChildren;
  "/files": typeof WorkspaceFilesRoute;
  "/home": typeof WorkspaceHomeRoute;
  "/settings/$section": typeof SettingsSectionRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/admin/$section": typeof WorkspaceAdminSectionRoute;
  "/apps/$appId": typeof WorkspaceAppsAppIdRoute;
  "/channels/$chatId": typeof WorkspaceChannelsChatIdRoute;
  "/chats/$chatId": typeof WorkspaceChatsChatIdRoute;
  "/documents/$documentId": typeof WorkspaceDocumentsDocumentIdRoute;
  "/admin/": typeof WorkspaceAdminIndexRoute;
  "/apps/": typeof WorkspaceAppsIndexRoute;
  "/channels/": typeof WorkspaceChannelsIndexRoute;
  "/chats/": typeof WorkspaceChatsIndexRoute;
  "/documents/": typeof WorkspaceDocumentsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/activity": typeof WorkspaceActivityRoute;
  "/calls": typeof WorkspaceCallsRoute;
  "/files": typeof WorkspaceFilesRoute;
  "/home": typeof WorkspaceHomeRoute;
  "/settings/$section": typeof SettingsSectionRoute;
  "/settings": typeof SettingsIndexRoute;
  "/admin/$section": typeof WorkspaceAdminSectionRoute;
  "/apps/$appId": typeof WorkspaceAppsAppIdRoute;
  "/channels/$chatId": typeof WorkspaceChannelsChatIdRoute;
  "/chats/$chatId": typeof WorkspaceChatsChatIdRoute;
  "/documents/$documentId": typeof WorkspaceDocumentsDocumentIdRoute;
  "/admin": typeof WorkspaceAdminIndexRoute;
  "/apps": typeof WorkspaceAppsIndexRoute;
  "/channels": typeof WorkspaceChannelsIndexRoute;
  "/chats": typeof WorkspaceChatsIndexRoute;
  "/documents": typeof WorkspaceDocumentsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_workspace": typeof WorkspaceRouteWithChildren;
  "/_workspace/activity": typeof WorkspaceActivityRoute;
  "/_workspace/apps": typeof WorkspaceAppsRouteWithChildren;
  "/_workspace/calls": typeof WorkspaceCallsRoute;
  "/_workspace/documents": typeof WorkspaceDocumentsRouteWithChildren;
  "/_workspace/files": typeof WorkspaceFilesRoute;
  "/_workspace/home": typeof WorkspaceHomeRoute;
  "/settings/$section": typeof SettingsSectionRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/_workspace/admin/$section": typeof WorkspaceAdminSectionRoute;
  "/_workspace/apps/$appId": typeof WorkspaceAppsAppIdRoute;
  "/_workspace/channels/$chatId": typeof WorkspaceChannelsChatIdRoute;
  "/_workspace/chats/$chatId": typeof WorkspaceChatsChatIdRoute;
  "/_workspace/documents/$documentId": typeof WorkspaceDocumentsDocumentIdRoute;
  "/_workspace/admin/": typeof WorkspaceAdminIndexRoute;
  "/_workspace/apps/": typeof WorkspaceAppsIndexRoute;
  "/_workspace/channels/": typeof WorkspaceChannelsIndexRoute;
  "/_workspace/chats/": typeof WorkspaceChatsIndexRoute;
  "/_workspace/documents/": typeof WorkspaceDocumentsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/activity"
    | "/apps"
    | "/calls"
    | "/documents"
    | "/files"
    | "/home"
    | "/settings/$section"
    | "/settings/"
    | "/admin/$section"
    | "/apps/$appId"
    | "/channels/$chatId"
    | "/chats/$chatId"
    | "/documents/$documentId"
    | "/admin/"
    | "/apps/"
    | "/channels/"
    | "/chats/"
    | "/documents/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/activity"
    | "/calls"
    | "/files"
    | "/home"
    | "/settings/$section"
    | "/settings"
    | "/admin/$section"
    | "/apps/$appId"
    | "/channels/$chatId"
    | "/chats/$chatId"
    | "/documents/$documentId"
    | "/admin"
    | "/apps"
    | "/channels"
    | "/chats"
    | "/documents";
  id:
    | "__root__"
    | "/"
    | "/_workspace"
    | "/_workspace/activity"
    | "/_workspace/apps"
    | "/_workspace/calls"
    | "/_workspace/documents"
    | "/_workspace/files"
    | "/_workspace/home"
    | "/settings/$section"
    | "/settings/"
    | "/_workspace/admin/$section"
    | "/_workspace/apps/$appId"
    | "/_workspace/channels/$chatId"
    | "/_workspace/chats/$chatId"
    | "/_workspace/documents/$documentId"
    | "/_workspace/admin/"
    | "/_workspace/apps/"
    | "/_workspace/channels/"
    | "/_workspace/chats/"
    | "/_workspace/documents/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WorkspaceRoute: typeof WorkspaceRouteWithChildren;
  SettingsSectionRoute: typeof SettingsSectionRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_workspace": {
      id: "/_workspace";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof WorkspaceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_workspace/activity": {
      id: "/_workspace/activity";
      path: "/activity";
      fullPath: "/activity";
      preLoaderRoute: typeof WorkspaceActivityRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/apps": {
      id: "/_workspace/apps";
      path: "/apps";
      fullPath: "/apps";
      preLoaderRoute: typeof WorkspaceAppsRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/calls": {
      id: "/_workspace/calls";
      path: "/calls";
      fullPath: "/calls";
      preLoaderRoute: typeof WorkspaceCallsRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/documents": {
      id: "/_workspace/documents";
      path: "/documents";
      fullPath: "/documents";
      preLoaderRoute: typeof WorkspaceDocumentsRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/files": {
      id: "/_workspace/files";
      path: "/files";
      fullPath: "/files";
      preLoaderRoute: typeof WorkspaceFilesRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/home": {
      id: "/_workspace/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof WorkspaceHomeRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/$section": {
      id: "/settings/$section";
      path: "/settings/$section";
      fullPath: "/settings/$section";
      preLoaderRoute: typeof SettingsSectionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_workspace/admin/": {
      id: "/_workspace/admin/";
      path: "/admin";
      fullPath: "/admin/";
      preLoaderRoute: typeof WorkspaceAdminIndexRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/admin/$section": {
      id: "/_workspace/admin/$section";
      path: "/admin/$section";
      fullPath: "/admin/$section";
      preLoaderRoute: typeof WorkspaceAdminSectionRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/apps/": {
      id: "/_workspace/apps/";
      path: "/";
      fullPath: "/apps/";
      preLoaderRoute: typeof WorkspaceAppsIndexRouteImport;
      parentRoute: typeof WorkspaceAppsRoute;
    };
    "/_workspace/apps/$appId": {
      id: "/_workspace/apps/$appId";
      path: "/$appId";
      fullPath: "/apps/$appId";
      preLoaderRoute: typeof WorkspaceAppsAppIdRouteImport;
      parentRoute: typeof WorkspaceAppsRoute;
    };
    "/_workspace/channels/": {
      id: "/_workspace/channels/";
      path: "/channels";
      fullPath: "/channels/";
      preLoaderRoute: typeof WorkspaceChannelsIndexRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/channels/$chatId": {
      id: "/_workspace/channels/$chatId";
      path: "/channels/$chatId";
      fullPath: "/channels/$chatId";
      preLoaderRoute: typeof WorkspaceChannelsChatIdRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/chats/": {
      id: "/_workspace/chats/";
      path: "/chats";
      fullPath: "/chats/";
      preLoaderRoute: typeof WorkspaceChatsIndexRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/chats/$chatId": {
      id: "/_workspace/chats/$chatId";
      path: "/chats/$chatId";
      fullPath: "/chats/$chatId";
      preLoaderRoute: typeof WorkspaceChatsChatIdRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/documents/": {
      id: "/_workspace/documents/";
      path: "/";
      fullPath: "/documents/";
      preLoaderRoute: typeof WorkspaceDocumentsIndexRouteImport;
      parentRoute: typeof WorkspaceDocumentsRoute;
    };
    "/_workspace/documents/$documentId": {
      id: "/_workspace/documents/$documentId";
      path: "/$documentId";
      fullPath: "/documents/$documentId";
      preLoaderRoute: typeof WorkspaceDocumentsDocumentIdRouteImport;
      parentRoute: typeof WorkspaceDocumentsRoute;
    };
  }
}

interface WorkspaceAppsRouteChildren {
  WorkspaceAppsAppIdRoute: typeof WorkspaceAppsAppIdRoute;
  WorkspaceAppsIndexRoute: typeof WorkspaceAppsIndexRoute;
}

const WorkspaceAppsRouteChildren: WorkspaceAppsRouteChildren = {
  WorkspaceAppsAppIdRoute: WorkspaceAppsAppIdRoute,
  WorkspaceAppsIndexRoute: WorkspaceAppsIndexRoute,
};

const WorkspaceAppsRouteWithChildren = WorkspaceAppsRoute._addFileChildren(
  WorkspaceAppsRouteChildren,
);

interface WorkspaceDocumentsRouteChildren {
  WorkspaceDocumentsDocumentIdRoute: typeof WorkspaceDocumentsDocumentIdRoute;
  WorkspaceDocumentsIndexRoute: typeof WorkspaceDocumentsIndexRoute;
}

const WorkspaceDocumentsRouteChildren: WorkspaceDocumentsRouteChildren = {
  WorkspaceDocumentsDocumentIdRoute: WorkspaceDocumentsDocumentIdRoute,
  WorkspaceDocumentsIndexRoute: WorkspaceDocumentsIndexRoute,
};

const WorkspaceDocumentsRouteWithChildren =
  WorkspaceDocumentsRoute._addFileChildren(WorkspaceDocumentsRouteChildren);

interface WorkspaceRouteChildren {
  WorkspaceActivityRoute: typeof WorkspaceActivityRoute;
  WorkspaceAppsRoute: typeof WorkspaceAppsRouteWithChildren;
  WorkspaceCallsRoute: typeof WorkspaceCallsRoute;
  WorkspaceDocumentsRoute: typeof WorkspaceDocumentsRouteWithChildren;
  WorkspaceFilesRoute: typeof WorkspaceFilesRoute;
  WorkspaceHomeRoute: typeof WorkspaceHomeRoute;
  WorkspaceAdminSectionRoute: typeof WorkspaceAdminSectionRoute;
  WorkspaceChannelsChatIdRoute: typeof WorkspaceChannelsChatIdRoute;
  WorkspaceChatsChatIdRoute: typeof WorkspaceChatsChatIdRoute;
  WorkspaceAdminIndexRoute: typeof WorkspaceAdminIndexRoute;
  WorkspaceChannelsIndexRoute: typeof WorkspaceChannelsIndexRoute;
  WorkspaceChatsIndexRoute: typeof WorkspaceChatsIndexRoute;
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceActivityRoute: WorkspaceActivityRoute,
  WorkspaceAppsRoute: WorkspaceAppsRouteWithChildren,
  WorkspaceCallsRoute: WorkspaceCallsRoute,
  WorkspaceDocumentsRoute: WorkspaceDocumentsRouteWithChildren,
  WorkspaceFilesRoute: WorkspaceFilesRoute,
  WorkspaceHomeRoute: WorkspaceHomeRoute,
  WorkspaceAdminSectionRoute: WorkspaceAdminSectionRoute,
  WorkspaceChannelsChatIdRoute: WorkspaceChannelsChatIdRoute,
  WorkspaceChatsChatIdRoute: WorkspaceChatsChatIdRoute,
  WorkspaceAdminIndexRoute: WorkspaceAdminIndexRoute,
  WorkspaceChannelsIndexRoute: WorkspaceChannelsIndexRoute,
  WorkspaceChatsIndexRoute: WorkspaceChatsIndexRoute,
};

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
