// Generated from packages/happy-desktop-ui/src/theme.css. Do not hand-edit.
use gpui::{Rgba, rgba};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ThemeRole {
    HappyScrollbarColor,
    HappyScrollbarQuietColor,
    HappyScrollbarActiveColor,
    HappyScrollbarInteractionColor,
    HappyScrollbarRestColor,
    HappyScrollbarSurfaceColor,
    Text,
    TextDestructive,
    TextSecondary,
    TextLink,
    DeleteAction,
    WarningCritical,
    Warning,
    Success,
    Surface,
    SurfaceRipple,
    SurfacePressed,
    SurfaceSelected,
    SurfacePressedOverlay,
    SurfaceHigh,
    SurfaceHighest,
    SurfaceInverse,
    TextInverse,
    PageCanvas,
    Divider,
    ShadowColor,
    ShadowSubtle,
    ShadowRail,
    ShadowFloating,
    ShadowElevated,
    OverlayBackdrop,
    OverlayPanel,
    GrouppedBackground,
    GrouppedChevron,
    GrouppedSectionTitle,
    HeaderBackground,
    HeaderTint,
    HeaderTintSecondary,
    SwitchTrackActive,
    SwitchTrackInactive,
    SwitchThumbActive,
    SwitchThumbInactive,
    FabBackground,
    FabBackgroundPressed,
    FabIcon,
    RadioActive,
    RadioInactive,
    RadioDot,
    ModalBorder,
    ButtonPrimaryBackground,
    ButtonPrimaryTint,
    ButtonPrimaryRipple,
    ButtonPrimaryDisabled,
    ButtonSecondaryTint,
    InputBackground,
    InputText,
    InputPlaceholder,
    BoxWarningBackground,
    BoxWarningBorder,
    BoxWarningText,
    BoxErrorBackground,
    BoxErrorBorder,
    BoxErrorText,
    ReviewAccent,
    ActivityElevatedLine,
    ActivityFailedLine,
    StatusConnected,
    StatusConnecting,
    StatusDisconnected,
    StatusError,
    StatusDefault,
    PermissionDefault,
    PermissionAcceptEdits,
    PermissionBypass,
    PermissionPlan,
    PermissionReadOnly,
    PermissionSafeYolo,
    PermissionYolo,
    PermissionButtonAllowBackground,
    PermissionButtonAllowText,
    PermissionButtonDenyBackground,
    PermissionButtonDenyText,
    PermissionButtonAllowAllBackground,
    PermissionButtonAllowAllText,
    PermissionButtonInactiveBackground,
    PermissionButtonInactiveBorder,
    PermissionButtonInactiveText,
    PermissionButtonSelectedBackground,
    PermissionButtonSelectedBorder,
    PermissionButtonSelectedText,
    DiffOutline,
    DiffSuccess,
    DiffError,
    DiffAddedBg,
    DiffAddedBorder,
    DiffAddedText,
    DiffRemovedBg,
    DiffRemovedBorder,
    DiffRemovedText,
    CodeComment,
    CodeString,
    CodeNumber,
    CodeKeyword,
    CodeType,
    CodeFunction,
    CodeVariable,
    CodeConstant,
    CodeOperator,
    CodePunctuation,
    CodeGutter,
    CodeGutterActive,
    CodeCaret,
    CodeSelection,
    CodeActiveLine,
    TerminalSelection,
    DiffContextBg,
    DiffContextText,
    DiffLineNumberBg,
    DiffLineNumberText,
    DiffHunkHeaderBg,
    DiffHunkHeaderText,
    DiffLeadingSpaceDot,
    DiffInlineAddedBg,
    DiffInlineAddedText,
    DiffInlineRemovedBg,
    DiffInlineRemovedText,
    UserMessageBackground,
    UserMessageText,
    AgentMessageText,
    AgentEventText,
    SyntaxKeyword,
    SyntaxString,
    SyntaxComment,
    SyntaxNumber,
    SyntaxFunction,
    SyntaxBracket1,
    SyntaxBracket2,
    SyntaxBracket3,
    SyntaxBracket4,
    SyntaxBracket5,
    SyntaxDefault,
    GitBranchText,
    GitFileCountText,
    GitAddedText,
    GitRemovedText,
    GitStatusNew,
    GitStatusModified,
    GitStatusRenamed,
    GitStatusDeleted,
    FileCode,
    FileData,
    FileStyle,
    FileImage,
    FileVideo,
    FileAudio,
    FileShell,
    FileSecret,
    FileArchive,
    FileProse,
    FileConfig,
    FileDirectory,
    FileOther,
    FilePathText,
    TerminalBackground,
    TerminalPrompt,
    TerminalCommand,
    TerminalStdout,
    TerminalStderr,
    TerminalError,
    TerminalEmptyOutput,
    NlKindColor,
    NlKindSoft,
}

impl ThemeRole {
    pub const ALL: [Self; 172] = [
        Self::HappyScrollbarColor,
        Self::HappyScrollbarQuietColor,
        Self::HappyScrollbarActiveColor,
        Self::HappyScrollbarInteractionColor,
        Self::HappyScrollbarRestColor,
        Self::HappyScrollbarSurfaceColor,
        Self::Text,
        Self::TextDestructive,
        Self::TextSecondary,
        Self::TextLink,
        Self::DeleteAction,
        Self::WarningCritical,
        Self::Warning,
        Self::Success,
        Self::Surface,
        Self::SurfaceRipple,
        Self::SurfacePressed,
        Self::SurfaceSelected,
        Self::SurfacePressedOverlay,
        Self::SurfaceHigh,
        Self::SurfaceHighest,
        Self::SurfaceInverse,
        Self::TextInverse,
        Self::PageCanvas,
        Self::Divider,
        Self::ShadowColor,
        Self::ShadowSubtle,
        Self::ShadowRail,
        Self::ShadowFloating,
        Self::ShadowElevated,
        Self::OverlayBackdrop,
        Self::OverlayPanel,
        Self::GrouppedBackground,
        Self::GrouppedChevron,
        Self::GrouppedSectionTitle,
        Self::HeaderBackground,
        Self::HeaderTint,
        Self::HeaderTintSecondary,
        Self::SwitchTrackActive,
        Self::SwitchTrackInactive,
        Self::SwitchThumbActive,
        Self::SwitchThumbInactive,
        Self::FabBackground,
        Self::FabBackgroundPressed,
        Self::FabIcon,
        Self::RadioActive,
        Self::RadioInactive,
        Self::RadioDot,
        Self::ModalBorder,
        Self::ButtonPrimaryBackground,
        Self::ButtonPrimaryTint,
        Self::ButtonPrimaryRipple,
        Self::ButtonPrimaryDisabled,
        Self::ButtonSecondaryTint,
        Self::InputBackground,
        Self::InputText,
        Self::InputPlaceholder,
        Self::BoxWarningBackground,
        Self::BoxWarningBorder,
        Self::BoxWarningText,
        Self::BoxErrorBackground,
        Self::BoxErrorBorder,
        Self::BoxErrorText,
        Self::ReviewAccent,
        Self::ActivityElevatedLine,
        Self::ActivityFailedLine,
        Self::StatusConnected,
        Self::StatusConnecting,
        Self::StatusDisconnected,
        Self::StatusError,
        Self::StatusDefault,
        Self::PermissionDefault,
        Self::PermissionAcceptEdits,
        Self::PermissionBypass,
        Self::PermissionPlan,
        Self::PermissionReadOnly,
        Self::PermissionSafeYolo,
        Self::PermissionYolo,
        Self::PermissionButtonAllowBackground,
        Self::PermissionButtonAllowText,
        Self::PermissionButtonDenyBackground,
        Self::PermissionButtonDenyText,
        Self::PermissionButtonAllowAllBackground,
        Self::PermissionButtonAllowAllText,
        Self::PermissionButtonInactiveBackground,
        Self::PermissionButtonInactiveBorder,
        Self::PermissionButtonInactiveText,
        Self::PermissionButtonSelectedBackground,
        Self::PermissionButtonSelectedBorder,
        Self::PermissionButtonSelectedText,
        Self::DiffOutline,
        Self::DiffSuccess,
        Self::DiffError,
        Self::DiffAddedBg,
        Self::DiffAddedBorder,
        Self::DiffAddedText,
        Self::DiffRemovedBg,
        Self::DiffRemovedBorder,
        Self::DiffRemovedText,
        Self::CodeComment,
        Self::CodeString,
        Self::CodeNumber,
        Self::CodeKeyword,
        Self::CodeType,
        Self::CodeFunction,
        Self::CodeVariable,
        Self::CodeConstant,
        Self::CodeOperator,
        Self::CodePunctuation,
        Self::CodeGutter,
        Self::CodeGutterActive,
        Self::CodeCaret,
        Self::CodeSelection,
        Self::CodeActiveLine,
        Self::TerminalSelection,
        Self::DiffContextBg,
        Self::DiffContextText,
        Self::DiffLineNumberBg,
        Self::DiffLineNumberText,
        Self::DiffHunkHeaderBg,
        Self::DiffHunkHeaderText,
        Self::DiffLeadingSpaceDot,
        Self::DiffInlineAddedBg,
        Self::DiffInlineAddedText,
        Self::DiffInlineRemovedBg,
        Self::DiffInlineRemovedText,
        Self::UserMessageBackground,
        Self::UserMessageText,
        Self::AgentMessageText,
        Self::AgentEventText,
        Self::SyntaxKeyword,
        Self::SyntaxString,
        Self::SyntaxComment,
        Self::SyntaxNumber,
        Self::SyntaxFunction,
        Self::SyntaxBracket1,
        Self::SyntaxBracket2,
        Self::SyntaxBracket3,
        Self::SyntaxBracket4,
        Self::SyntaxBracket5,
        Self::SyntaxDefault,
        Self::GitBranchText,
        Self::GitFileCountText,
        Self::GitAddedText,
        Self::GitRemovedText,
        Self::GitStatusNew,
        Self::GitStatusModified,
        Self::GitStatusRenamed,
        Self::GitStatusDeleted,
        Self::FileCode,
        Self::FileData,
        Self::FileStyle,
        Self::FileImage,
        Self::FileVideo,
        Self::FileAudio,
        Self::FileShell,
        Self::FileSecret,
        Self::FileArchive,
        Self::FileProse,
        Self::FileConfig,
        Self::FileDirectory,
        Self::FileOther,
        Self::FilePathText,
        Self::TerminalBackground,
        Self::TerminalPrompt,
        Self::TerminalCommand,
        Self::TerminalStdout,
        Self::TerminalStderr,
        Self::TerminalError,
        Self::TerminalEmptyOutput,
        Self::NlKindColor,
        Self::NlKindSoft,
    ];
    pub const fn name(self) -> &'static str {
        match self {
            Self::HappyScrollbarColor => "happy-scrollbar-color",
            Self::HappyScrollbarQuietColor => "happy-scrollbar-quiet-color",
            Self::HappyScrollbarActiveColor => "happy-scrollbar-active-color",
            Self::HappyScrollbarInteractionColor => "happy-scrollbar-interaction-color",
            Self::HappyScrollbarRestColor => "happy-scrollbar-rest-color",
            Self::HappyScrollbarSurfaceColor => "happy-scrollbar-surface-color",
            Self::Text => "text",
            Self::TextDestructive => "text-destructive",
            Self::TextSecondary => "text-secondary",
            Self::TextLink => "text-link",
            Self::DeleteAction => "delete-action",
            Self::WarningCritical => "warning-critical",
            Self::Warning => "warning",
            Self::Success => "success",
            Self::Surface => "surface",
            Self::SurfaceRipple => "surface-ripple",
            Self::SurfacePressed => "surface-pressed",
            Self::SurfaceSelected => "surface-selected",
            Self::SurfacePressedOverlay => "surface-pressed-overlay",
            Self::SurfaceHigh => "surface-high",
            Self::SurfaceHighest => "surface-highest",
            Self::SurfaceInverse => "surface-inverse",
            Self::TextInverse => "text-inverse",
            Self::PageCanvas => "page-canvas",
            Self::Divider => "divider",
            Self::ShadowColor => "shadow-color",
            Self::ShadowSubtle => "shadow-subtle",
            Self::ShadowRail => "shadow-rail",
            Self::ShadowFloating => "shadow-floating",
            Self::ShadowElevated => "shadow-elevated",
            Self::OverlayBackdrop => "overlay-backdrop",
            Self::OverlayPanel => "overlay-panel",
            Self::GrouppedBackground => "groupped-background",
            Self::GrouppedChevron => "groupped-chevron",
            Self::GrouppedSectionTitle => "groupped-section-title",
            Self::HeaderBackground => "header-background",
            Self::HeaderTint => "header-tint",
            Self::HeaderTintSecondary => "header-tint-secondary",
            Self::SwitchTrackActive => "switch-track-active",
            Self::SwitchTrackInactive => "switch-track-inactive",
            Self::SwitchThumbActive => "switch-thumb-active",
            Self::SwitchThumbInactive => "switch-thumb-inactive",
            Self::FabBackground => "fab-background",
            Self::FabBackgroundPressed => "fab-background-pressed",
            Self::FabIcon => "fab-icon",
            Self::RadioActive => "radio-active",
            Self::RadioInactive => "radio-inactive",
            Self::RadioDot => "radio-dot",
            Self::ModalBorder => "modal-border",
            Self::ButtonPrimaryBackground => "button-primary-background",
            Self::ButtonPrimaryTint => "button-primary-tint",
            Self::ButtonPrimaryRipple => "button-primary-ripple",
            Self::ButtonPrimaryDisabled => "button-primary-disabled",
            Self::ButtonSecondaryTint => "button-secondary-tint",
            Self::InputBackground => "input-background",
            Self::InputText => "input-text",
            Self::InputPlaceholder => "input-placeholder",
            Self::BoxWarningBackground => "box-warning-background",
            Self::BoxWarningBorder => "box-warning-border",
            Self::BoxWarningText => "box-warning-text",
            Self::BoxErrorBackground => "box-error-background",
            Self::BoxErrorBorder => "box-error-border",
            Self::BoxErrorText => "box-error-text",
            Self::ReviewAccent => "review-accent",
            Self::ActivityElevatedLine => "activity-elevated-line",
            Self::ActivityFailedLine => "activity-failed-line",
            Self::StatusConnected => "status-connected",
            Self::StatusConnecting => "status-connecting",
            Self::StatusDisconnected => "status-disconnected",
            Self::StatusError => "status-error",
            Self::StatusDefault => "status-default",
            Self::PermissionDefault => "permission-default",
            Self::PermissionAcceptEdits => "permission-accept-edits",
            Self::PermissionBypass => "permission-bypass",
            Self::PermissionPlan => "permission-plan",
            Self::PermissionReadOnly => "permission-read-only",
            Self::PermissionSafeYolo => "permission-safe-yolo",
            Self::PermissionYolo => "permission-yolo",
            Self::PermissionButtonAllowBackground => "permission-button-allow-background",
            Self::PermissionButtonAllowText => "permission-button-allow-text",
            Self::PermissionButtonDenyBackground => "permission-button-deny-background",
            Self::PermissionButtonDenyText => "permission-button-deny-text",
            Self::PermissionButtonAllowAllBackground => "permission-button-allow-all-background",
            Self::PermissionButtonAllowAllText => "permission-button-allow-all-text",
            Self::PermissionButtonInactiveBackground => "permission-button-inactive-background",
            Self::PermissionButtonInactiveBorder => "permission-button-inactive-border",
            Self::PermissionButtonInactiveText => "permission-button-inactive-text",
            Self::PermissionButtonSelectedBackground => "permission-button-selected-background",
            Self::PermissionButtonSelectedBorder => "permission-button-selected-border",
            Self::PermissionButtonSelectedText => "permission-button-selected-text",
            Self::DiffOutline => "diff-outline",
            Self::DiffSuccess => "diff-success",
            Self::DiffError => "diff-error",
            Self::DiffAddedBg => "diff-added-bg",
            Self::DiffAddedBorder => "diff-added-border",
            Self::DiffAddedText => "diff-added-text",
            Self::DiffRemovedBg => "diff-removed-bg",
            Self::DiffRemovedBorder => "diff-removed-border",
            Self::DiffRemovedText => "diff-removed-text",
            Self::CodeComment => "code-comment",
            Self::CodeString => "code-string",
            Self::CodeNumber => "code-number",
            Self::CodeKeyword => "code-keyword",
            Self::CodeType => "code-type",
            Self::CodeFunction => "code-function",
            Self::CodeVariable => "code-variable",
            Self::CodeConstant => "code-constant",
            Self::CodeOperator => "code-operator",
            Self::CodePunctuation => "code-punctuation",
            Self::CodeGutter => "code-gutter",
            Self::CodeGutterActive => "code-gutter-active",
            Self::CodeCaret => "code-caret",
            Self::CodeSelection => "code-selection",
            Self::CodeActiveLine => "code-active-line",
            Self::TerminalSelection => "terminal-selection",
            Self::DiffContextBg => "diff-context-bg",
            Self::DiffContextText => "diff-context-text",
            Self::DiffLineNumberBg => "diff-line-number-bg",
            Self::DiffLineNumberText => "diff-line-number-text",
            Self::DiffHunkHeaderBg => "diff-hunk-header-bg",
            Self::DiffHunkHeaderText => "diff-hunk-header-text",
            Self::DiffLeadingSpaceDot => "diff-leading-space-dot",
            Self::DiffInlineAddedBg => "diff-inline-added-bg",
            Self::DiffInlineAddedText => "diff-inline-added-text",
            Self::DiffInlineRemovedBg => "diff-inline-removed-bg",
            Self::DiffInlineRemovedText => "diff-inline-removed-text",
            Self::UserMessageBackground => "user-message-background",
            Self::UserMessageText => "user-message-text",
            Self::AgentMessageText => "agent-message-text",
            Self::AgentEventText => "agent-event-text",
            Self::SyntaxKeyword => "syntax-keyword",
            Self::SyntaxString => "syntax-string",
            Self::SyntaxComment => "syntax-comment",
            Self::SyntaxNumber => "syntax-number",
            Self::SyntaxFunction => "syntax-function",
            Self::SyntaxBracket1 => "syntax-bracket-1",
            Self::SyntaxBracket2 => "syntax-bracket-2",
            Self::SyntaxBracket3 => "syntax-bracket-3",
            Self::SyntaxBracket4 => "syntax-bracket-4",
            Self::SyntaxBracket5 => "syntax-bracket-5",
            Self::SyntaxDefault => "syntax-default",
            Self::GitBranchText => "git-branch-text",
            Self::GitFileCountText => "git-file-count-text",
            Self::GitAddedText => "git-added-text",
            Self::GitRemovedText => "git-removed-text",
            Self::GitStatusNew => "git-status-new",
            Self::GitStatusModified => "git-status-modified",
            Self::GitStatusRenamed => "git-status-renamed",
            Self::GitStatusDeleted => "git-status-deleted",
            Self::FileCode => "file-code",
            Self::FileData => "file-data",
            Self::FileStyle => "file-style",
            Self::FileImage => "file-image",
            Self::FileVideo => "file-video",
            Self::FileAudio => "file-audio",
            Self::FileShell => "file-shell",
            Self::FileSecret => "file-secret",
            Self::FileArchive => "file-archive",
            Self::FileProse => "file-prose",
            Self::FileConfig => "file-config",
            Self::FileDirectory => "file-directory",
            Self::FileOther => "file-other",
            Self::FilePathText => "file-path-text",
            Self::TerminalBackground => "terminal-background",
            Self::TerminalPrompt => "terminal-prompt",
            Self::TerminalCommand => "terminal-command",
            Self::TerminalStdout => "terminal-stdout",
            Self::TerminalStderr => "terminal-stderr",
            Self::TerminalError => "terminal-error",
            Self::TerminalEmptyOutput => "terminal-empty-output",
            Self::NlKindColor => "nl-kind-color",
            Self::NlKindSoft => "nl-kind-soft",
        }
    }
    pub fn resolve(self, dark: bool) -> Rgba {
        let value = match (self, dark) {
            (Self::HappyScrollbarColor, _) => 0x00000000,
            (Self::HappyScrollbarQuietColor, _) => 0x80808052,
            (Self::HappyScrollbarActiveColor, _) => 0x80808080,
            (Self::HappyScrollbarInteractionColor, _) => 0x808080ad,
            (Self::HappyScrollbarRestColor, _) => 0x00000000,
            (Self::HappyScrollbarSurfaceColor, _) => 0x00000000,
            (Self::Text, false) => 0x000000ff,
            (Self::Text, true) => 0xffffffff,
            (Self::TextDestructive, false) => 0xf44336ff,
            (Self::TextDestructive, true) => 0xf48fb1ff,
            (Self::TextSecondary, false) => 0x49454fff,
            (Self::TextSecondary, true) => 0xcac4d0ff,
            (Self::TextLink, _) => 0x2bacccff,
            (Self::DeleteAction, _) => 0xff6b6bff,
            (Self::WarningCritical, false) => 0xff3b30ff,
            (Self::WarningCritical, true) => 0xff453aff,
            (Self::Warning, _) => 0x8e8e93ff,
            (Self::Success, false) => 0x34c759ff,
            (Self::Success, true) => 0x32d74bff,
            (Self::Surface, false) => 0xffffffff,
            (Self::Surface, true) => 0x212121ff,
            (Self::SurfaceRipple, false) => 0x00000014,
            (Self::SurfaceRipple, true) => 0xffffff14,
            (Self::SurfacePressed, false) => 0xf0f0f2ff,
            (Self::SurfacePressed, true) => 0x2c2c2eff,
            (Self::SurfaceSelected, false) => 0xeaeaeaff,
            (Self::SurfaceSelected, true) => 0x2c2c2eff,
            (Self::SurfacePressedOverlay, _) => 0x00000000,
            (Self::SurfaceHigh, false) => 0xf8f8f8ff,
            (Self::SurfaceHigh, true) => 0x171717ff,
            (Self::SurfaceHighest, false) => 0xf0f0f0ff,
            (Self::SurfaceHighest, true) => 0x292929ff,
            (Self::SurfaceInverse, false) => 0x1c1c1eff,
            (Self::SurfaceInverse, true) => 0xf2f2f7ff,
            (Self::TextInverse, false) => 0xffffffff,
            (Self::TextInverse, true) => 0x1c1c1eff,
            (Self::PageCanvas, _) => 0xffffffff,
            (Self::Divider, false) => 0xeaeaeaff,
            (Self::Divider, true) => 0x292929ff,
            (Self::ShadowColor, _) => 0x0000001a,
            (Self::ShadowSubtle, _) => 0x0000003d,
            (Self::ShadowRail, _) => 0x00000047,
            (Self::ShadowFloating, _) => 0x00000073,
            (Self::ShadowElevated, _) => 0x00000080,
            (Self::OverlayBackdrop, _) => 0x0f0f0fbf,
            (Self::OverlayPanel, _) => 0x0000007a,
            (Self::GrouppedBackground, false) => 0xf5f5f5ff,
            (Self::GrouppedBackground, true) => 0x1e1e1eff,
            (Self::GrouppedChevron, false) => 0x49454fff,
            (Self::GrouppedChevron, true) => 0xcac4d0ff,
            (Self::GrouppedSectionTitle, false) => 0x49454fff,
            (Self::GrouppedSectionTitle, true) => 0xcac4d0ff,
            (Self::HeaderBackground, false) => 0xffffffff,
            (Self::HeaderBackground, true) => 0x212121ff,
            (Self::HeaderTint, false) => 0x18171cff,
            (Self::HeaderTint, true) => 0xffffffff,
            (Self::HeaderTintSecondary, false) => 0x666666ff,
            (Self::HeaderTintSecondary, true) => 0x8e8e93ff,
            (Self::SwitchTrackActive, _) => 0x1976d2ff,
            (Self::SwitchTrackInactive, false) => 0xddddddff,
            (Self::SwitchTrackInactive, true) => 0x3a393fff,
            (Self::SwitchThumbActive, _) => 0xffffffff,
            (Self::SwitchThumbInactive, _) => 0x767577ff,
            (Self::FabBackground, false) => 0x000000ff,
            (Self::FabBackground, true) => 0xffffffff,
            (Self::FabBackgroundPressed, false) => 0x1a1a1aff,
            (Self::FabBackgroundPressed, true) => 0xf0f0f0ff,
            (Self::FabIcon, false) => 0xffffffff,
            (Self::FabIcon, true) => 0x000000ff,
            (Self::RadioActive, false) => 0x007affff,
            (Self::RadioActive, true) => 0x0a84ffff,
            (Self::RadioInactive, false) => 0xc0c0c0ff,
            (Self::RadioInactive, true) => 0x48484aff,
            (Self::RadioDot, false) => 0x007affff,
            (Self::RadioDot, true) => 0x0a84ffff,
            (Self::ModalBorder, false) => 0x0000001a,
            (Self::ModalBorder, true) => 0xffffff1a,
            (Self::ButtonPrimaryBackground, _) => 0x000000ff,
            (Self::ButtonPrimaryTint, _) => 0xffffffff,
            (Self::ButtonPrimaryRipple, _) => 0xffffff29,
            (Self::ButtonPrimaryDisabled, _) => 0xc0c0c0ff,
            (Self::ButtonSecondaryTint, false) => 0x666666ff,
            (Self::ButtonSecondaryTint, true) => 0x8e8e93ff,
            (Self::InputBackground, false) => 0xf5f5f5ff,
            (Self::InputBackground, true) => 0x303030ff,
            (Self::InputText, false) => 0x000000ff,
            (Self::InputText, true) => 0xffffffff,
            (Self::InputPlaceholder, false) => 0x999999ff,
            (Self::InputPlaceholder, true) => 0x8e8e93ff,
            (Self::BoxWarningBackground, false) => 0xfff8f0ff,
            (Self::BoxWarningBackground, true) => 0xff9f0a26,
            (Self::BoxWarningBorder, false) => 0xff9500ff,
            (Self::BoxWarningBorder, true) => 0xff9f0aff,
            (Self::BoxWarningText, false) => 0xff9500ff,
            (Self::BoxWarningText, true) => 0xffab00ff,
            (Self::BoxErrorBackground, false) => 0xfff0f0ff,
            (Self::BoxErrorBackground, true) => 0xff453a26,
            (Self::BoxErrorBorder, false) => 0xff3b30ff,
            (Self::BoxErrorBorder, true) => 0xff453aff,
            (Self::BoxErrorText, false) => 0xff3b30ff,
            (Self::BoxErrorText, true) => 0xff6b6bff,
            (Self::ReviewAccent, false) => 0xa3690fff,
            (Self::ReviewAccent, true) => 0xc8924eff,
            (Self::ActivityElevatedLine, false) => 0x412a06ff,
            (Self::ActivityElevatedLine, true) => 0xe9d3b8ff,
            (Self::ActivityFailedLine, false) => 0x661813ff,
            (Self::ActivityFailedLine, true) => 0xffb5b0ff,
            (Self::StatusConnected, _) => 0x34c759ff,
            (Self::StatusConnecting, false) => 0x007affff,
            (Self::StatusConnecting, true) => 0xffffffff,
            (Self::StatusDisconnected, false) => 0x999999ff,
            (Self::StatusDisconnected, true) => 0x8e8e93ff,
            (Self::StatusError, false) => 0xff3b30ff,
            (Self::StatusError, true) => 0xff453aff,
            (Self::StatusDefault, _) => 0x8e8e93ff,
            (Self::PermissionDefault, _) => 0x8e8e93ff,
            (Self::PermissionAcceptEdits, false) => 0x007affff,
            (Self::PermissionAcceptEdits, true) => 0x0a84ffff,
            (Self::PermissionBypass, false) => 0xff9500ff,
            (Self::PermissionBypass, true) => 0xff9f0aff,
            (Self::PermissionPlan, false) => 0x34c759ff,
            (Self::PermissionPlan, true) => 0x32d74bff,
            (Self::PermissionReadOnly, false) => 0x8b8b8dff,
            (Self::PermissionReadOnly, true) => 0x98989dff,
            (Self::PermissionSafeYolo, false) => 0xff6b35ff,
            (Self::PermissionSafeYolo, true) => 0xff7a4cff,
            (Self::PermissionYolo, false) => 0xdc143cff,
            (Self::PermissionYolo, true) => 0xff453aff,
            (Self::PermissionButtonAllowBackground, false) => 0x34c759ff,
            (Self::PermissionButtonAllowBackground, true) => 0x32d74bff,
            (Self::PermissionButtonAllowText, _) => 0xffffffff,
            (Self::PermissionButtonDenyBackground, false) => 0xff3b30ff,
            (Self::PermissionButtonDenyBackground, true) => 0xff453aff,
            (Self::PermissionButtonDenyText, _) => 0xffffffff,
            (Self::PermissionButtonAllowAllBackground, false) => 0x007affff,
            (Self::PermissionButtonAllowAllBackground, true) => 0x0a84ffff,
            (Self::PermissionButtonAllowAllText, _) => 0xffffffff,
            (Self::PermissionButtonInactiveBackground, false) => 0xe5e5eaff,
            (Self::PermissionButtonInactiveBackground, true) => 0x2c2c2eff,
            (Self::PermissionButtonInactiveBorder, false) => 0xd1d1d6ff,
            (Self::PermissionButtonInactiveBorder, true) => 0x38383aff,
            (Self::PermissionButtonInactiveText, _) => 0x8e8e93ff,
            (Self::PermissionButtonSelectedBackground, false) => 0xf2f2f7ff,
            (Self::PermissionButtonSelectedBackground, true) => 0x1c1c1eff,
            (Self::PermissionButtonSelectedBorder, false) => 0xd1d1d6ff,
            (Self::PermissionButtonSelectedBorder, true) => 0x38383aff,
            (Self::PermissionButtonSelectedText, false) => 0x3c3c43ff,
            (Self::PermissionButtonSelectedText, true) => 0xffffffff,
            (Self::DiffOutline, false) => 0xe0e0e0ff,
            (Self::DiffOutline, true) => 0x30363dff,
            (Self::DiffSuccess, false) => 0x28a745ff,
            (Self::DiffSuccess, true) => 0x3fb950ff,
            (Self::DiffError, false) => 0xdc3545ff,
            (Self::DiffError, true) => 0xf85149ff,
            (Self::DiffAddedBg, false) => 0xe6ffedff,
            (Self::DiffAddedBg, true) => 0x0d2e1fff,
            (Self::DiffAddedBorder, false) => 0x34d058ff,
            (Self::DiffAddedBorder, true) => 0x3fb950ff,
            (Self::DiffAddedText, false) => 0x24292eff,
            (Self::DiffAddedText, true) => 0xc9d1d9ff,
            (Self::DiffRemovedBg, false) => 0xffeef0ff,
            (Self::DiffRemovedBg, true) => 0x3f1b23ff,
            (Self::DiffRemovedBorder, false) => 0xd73a49ff,
            (Self::DiffRemovedBorder, true) => 0xf85149ff,
            (Self::DiffRemovedText, false) => 0x24292eff,
            (Self::DiffRemovedText, true) => 0xc9d1d9ff,
            (Self::CodeComment, _) => 0x737373ff,
            (Self::CodeString, false) => 0x199f43ff,
            (Self::CodeString, true) => 0x5ecc71ff,
            (Self::CodeNumber, false) => 0x1ca1c7ff,
            (Self::CodeNumber, true) => 0x68cdf2ff,
            (Self::CodeKeyword, false) => 0xd32a61ff,
            (Self::CodeKeyword, true) => 0xff678dff,
            (Self::CodeType, false) => 0xa631beff,
            (Self::CodeType, true) => 0xd568eaff,
            (Self::CodeFunction, false) => 0x693acfff,
            (Self::CodeFunction, true) => 0x9d6afbff,
            (Self::CodeVariable, false) => 0xd47628ff,
            (Self::CodeVariable, true) => 0xffa359ff,
            (Self::CodeConstant, false) => 0xd5a910ff,
            (Self::CodeConstant, true) => 0xffd452ff,
            (Self::CodeOperator, _) => 0x08c0efff,
            (Self::CodePunctuation, false) => 0x636363ff,
            (Self::CodePunctuation, true) => 0xa3a3a3ff,
            (Self::CodeGutter, _) => 0x737373ff,
            (Self::CodeGutterActive, false) => 0x525252ff,
            (Self::CodeGutterActive, true) => 0xa3a3a3ff,
            (Self::CodeCaret, false) => 0x000000ff,
            (Self::CodeCaret, true) => 0xffffffff,
            (Self::CodeSelection, false) => 0x00000024,
            (Self::CodeSelection, true) => 0xffffff2e,
            (Self::CodeActiveLine, false) => 0x0000000a,
            (Self::CodeActiveLine, true) => 0xffffff0d,
            (Self::TerminalSelection, false) => 0xd4d4d8ff,
            (Self::TerminalSelection, true) => 0x45454bff,
            (Self::DiffContextBg, false) => 0xf6f8faff,
            (Self::DiffContextBg, true) => 0x161b22ff,
            (Self::DiffContextText, false) => 0x586069ff,
            (Self::DiffContextText, true) => 0x8b949eff,
            (Self::DiffLineNumberBg, false) => 0xf6f8faff,
            (Self::DiffLineNumberBg, true) => 0x161b22ff,
            (Self::DiffLineNumberText, false) => 0x959da5ff,
            (Self::DiffLineNumberText, true) => 0x6e7681ff,
            (Self::DiffHunkHeaderBg, false) => 0xf1f8ffff,
            (Self::DiffHunkHeaderBg, true) => 0x161b22ff,
            (Self::DiffHunkHeaderText, false) => 0x005cc5ff,
            (Self::DiffHunkHeaderText, true) => 0x58a6ffff,
            (Self::DiffLeadingSpaceDot, false) => 0xe8e8e8ff,
            (Self::DiffLeadingSpaceDot, true) => 0x2a2a2aff,
            (Self::DiffInlineAddedBg, false) => 0xacffa6ff,
            (Self::DiffInlineAddedBg, true) => 0x2a5a2aff,
            (Self::DiffInlineAddedText, false) => 0x0a3f0aff,
            (Self::DiffInlineAddedText, true) => 0x7aff7aff,
            (Self::DiffInlineRemovedBg, false) => 0xffcecbff,
            (Self::DiffInlineRemovedBg, true) => 0x5a2a2aff,
            (Self::DiffInlineRemovedText, false) => 0x5a0a05ff,
            (Self::DiffInlineRemovedText, true) => 0xff7a7aff,
            (Self::UserMessageBackground, false) => 0xf0eee6ff,
            (Self::UserMessageBackground, true) => 0x2c2c2eff,
            (Self::UserMessageText, false) => 0x000000ff,
            (Self::UserMessageText, true) => 0xffffffff,
            (Self::AgentMessageText, false) => 0x000000ff,
            (Self::AgentMessageText, true) => 0xffffffff,
            (Self::AgentEventText, false) => 0x666666ff,
            (Self::AgentEventText, true) => 0x8e8e93ff,
            (Self::SyntaxKeyword, false) => 0x1d4ed8ff,
            (Self::SyntaxKeyword, true) => 0x569cd6ff,
            (Self::SyntaxString, false) => 0x059669ff,
            (Self::SyntaxString, true) => 0xce9178ff,
            (Self::SyntaxComment, false) => 0x6b7280ff,
            (Self::SyntaxComment, true) => 0x6a9955ff,
            (Self::SyntaxNumber, false) => 0x0891b2ff,
            (Self::SyntaxNumber, true) => 0xb5cea8ff,
            (Self::SyntaxFunction, false) => 0x9333eaff,
            (Self::SyntaxFunction, true) => 0xdcdcaaff,
            (Self::SyntaxBracket1, false) => 0xff6b6bff,
            (Self::SyntaxBracket1, true) => 0xffd700ff,
            (Self::SyntaxBracket2, false) => 0x4ecdc4ff,
            (Self::SyntaxBracket2, true) => 0xda70d6ff,
            (Self::SyntaxBracket3, false) => 0x45b7d1ff,
            (Self::SyntaxBracket3, true) => 0x179fffff,
            (Self::SyntaxBracket4, false) => 0xf7b731ff,
            (Self::SyntaxBracket4, true) => 0xff8c00ff,
            (Self::SyntaxBracket5, false) => 0x5f27cdff,
            (Self::SyntaxBracket5, true) => 0x00ff00ff,
            (Self::SyntaxDefault, false) => 0x374151ff,
            (Self::SyntaxDefault, true) => 0xd4d4d4ff,
            (Self::GitBranchText, false) => 0x6b7280ff,
            (Self::GitBranchText, true) => 0x8e8e93ff,
            (Self::GitFileCountText, false) => 0x6b7280ff,
            (Self::GitFileCountText, true) => 0x8e8e93ff,
            (Self::GitAddedText, false) => 0x22c55eff,
            (Self::GitAddedText, true) => 0x34c759ff,
            (Self::GitRemovedText, false) => 0xef4444ff,
            (Self::GitRemovedText, true) => 0xff453aff,
            (Self::GitStatusNew, false) => 0x2ea043ff,
            (Self::GitStatusNew, true) => 0x3fb950ff,
            (Self::GitStatusModified, false) => 0xc2820aff,
            (Self::GitStatusModified, true) => 0xe3b341ff,
            (Self::GitStatusRenamed, false) => 0x0969daff,
            (Self::GitStatusRenamed, true) => 0x58a6ffff,
            (Self::GitStatusDeleted, false) => 0xcf222eff,
            (Self::GitStatusDeleted, true) => 0xf85149ff,
            (Self::FileCode, false) => 0x2563ebff,
            (Self::FileCode, true) => 0x6ea8feff,
            (Self::FileData, false) => 0xb45309ff,
            (Self::FileData, true) => 0xe0a458ff,
            (Self::FileStyle, false) => 0x7c3aedff,
            (Self::FileStyle, true) => 0xb794f6ff,
            (Self::FileImage, false) => 0x0d9488ff,
            (Self::FileImage, true) => 0x4dd4c0ff,
            (Self::FileVideo, false) => 0xdb2777ff,
            (Self::FileVideo, true) => 0xf472b6ff,
            (Self::FileAudio, false) => 0xc026d3ff,
            (Self::FileAudio, true) => 0xe879f9ff,
            (Self::FileShell, false) => 0x475569ff,
            (Self::FileShell, true) => 0xa3b3c7ff,
            (Self::FileSecret, false) => 0xb91c1cff,
            (Self::FileSecret, true) => 0xff7b72ff,
            (Self::FileArchive, false) => 0xa16207ff,
            (Self::FileArchive, true) => 0xd9a441ff,
            (Self::FileProse, false) => 0x0e7490ff,
            (Self::FileProse, true) => 0x4cc9d9ff,
            (Self::FileConfig, false) => 0x6b7280ff,
            (Self::FileConfig, true) => 0x9ca3afff,
            (Self::FileDirectory, false) => 0x64748bff,
            (Self::FileDirectory, true) => 0x93a4b8ff,
            (Self::FileOther, false) => 0x6b7280ff,
            (Self::FileOther, true) => 0x9ca3afff,
            (Self::FilePathText, false) => 0x9a969eff,
            (Self::FilePathText, true) => 0x79747eff,
            (Self::TerminalBackground, _) => 0x1e1e1eff,
            (Self::TerminalPrompt, false) => 0x34c759ff,
            (Self::TerminalPrompt, true) => 0x32d74bff,
            (Self::TerminalCommand, _) => 0xe0e0e0ff,
            (Self::TerminalStdout, _) => 0xe0e0e0ff,
            (Self::TerminalStderr, _) => 0xffb86cff,
            (Self::TerminalError, false) => 0xff5555ff,
            (Self::TerminalError, true) => 0xff6b6bff,
            (Self::TerminalEmptyOutput, false) => 0x6272a4ff,
            (Self::TerminalEmptyOutput, true) => 0x7b7b93ff,
            (Self::NlKindColor, _) => 0x2bacccff,
            (Self::NlKindSoft, false) => 0xeaeaeaff,
            (Self::NlKindSoft, true) => 0x2c2c2eff,
        };
        rgba(value)
    }
}
