#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["fonttools==4.60.2"]
# ///
"""Build GPUI-safe icon fonts and generated Rust glyph constants.

The source TTF outlines and upstream PUA mappings stay unchanged. GPUI 0.2.2
requires every selectable custom font to map `m`; both icon fonts intentionally
do not, so the adapters point `m` at their zero-ink space glyph.
"""
from pathlib import Path
import hashlib
import subprocess
import re
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
UI = ROOT.parent / "happy-desktop-ui" / "src"
UI_FONT_DIR = UI / "assets" / "fonts"
FONT_DIR = ROOT / "assets" / "fonts"
OUT = ROOT / "src" / "ui" / "icon_data.rs"
SETS = (
    ("ionicons", "Ionicons.ttf", "Happy Ionicons", "ioniconsGlyphs.ts", 1357),
    ("octicons", "Octicons.ttf", "Happy Octicons", "octiconsGlyphs.ts", 331),
)


def adapt(source: Path, output: Path, family: str) -> None:
    font = TTFont(source, recalcTimestamp=False)
    font.recalcTimestamp = False
    source_cmap = font.getBestCmap()
    for table in font["cmap"].tables:
        table.cmap[ord("m")] = source_cmap[0x20]
    names = font["name"]
    values = {1: family, 2: "Regular", 3: f"{family} Regular", 4: f"{family} Regular", 6: family.replace(" ", "")}
    for record in names.names:
        if record.nameID in values:
            record.string = values[record.nameID].encode(
                "utf-16-be" if record.platformID in (0, 3) else "mac_roman"
            )
    font.save(output)


def glyphs(path: Path) -> list[tuple[str, int]]:
    text = path.read_text()
    pairs = re.findall(r'^\s*(?:"([^"]+)"|([a-zA-Z0-9_-]+)):\s*(0x[0-9a-fA-F]+|\d+),', text, re.M)
    return [(quoted or bare, int(value, 0)) for quoted, bare, value in pairs]


def rust_name(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()
    return ("GLYPH_" if value[:1].isdigit() else "") + value


parsed_maps = {}
for module, source_name, _, map_name, expected_count in SETS:
    authoritative = UI_FONT_DIR / source_name
    source = FONT_DIR / source_name
    authoritative_hash = hashlib.sha256(authoritative.read_bytes()).digest()
    source_hash = hashlib.sha256(source.read_bytes()).digest()
    if source_hash != authoritative_hash:
        raise RuntimeError(
            f"{source} does not match authoritative happy-desktop-ui font {authoritative}"
        )
    items = glyphs(UI / "vectorIcons" / map_name)
    if len(items) != expected_count:
        raise RuntimeError(
            f"expected {expected_count} parsed {module} glyphs, found {len(items)}"
        )
    parsed_maps[module] = items

OUT.parent.mkdir(parents=True, exist_ok=True)
modules = []
for module, source_name, family, _, _ in SETS:
    adapt(FONT_DIR / source_name, FONT_DIR / f"Happy{source_name}", family)
    items = parsed_maps[module]
    constants = [(rust_name(name), name, codepoint) for name, codepoint in items]
    names = [constant for constant, _, _ in constants]
    if len(names) != len(set(names)):
        raise RuntimeError(f"generated Rust name collision in {module}")
    lines = [f"pub mod {module} {{", "    use super::UpstreamIcon;", f'    pub const FAMILY: &str = "{family}";']
    for constant, name, codepoint in constants:
        lines.append(f'    /// Upstream `{name}`.')
        lines.append(f"    pub const {constant}: UpstreamIcon = UpstreamIcon::new(FAMILY, '\\u{{{codepoint:x}}}');")
    lines.append("}")
    modules.append("\n".join(lines))
OUT.write_text("""// Generated by scripts/build-icon-fonts.py. Do not hand-edit.\n#![allow(dead_code)]\n\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct UpstreamIcon {\n    pub family: &'static str,\n    pub glyph: char,\n}\n\nimpl UpstreamIcon {\n    pub const fn new(family: &'static str, glyph: char) -> Self {\n        Self { family, glyph }\n    }\n}\n\n""" + "\n\n".join(modules) + "\n")
subprocess.run(["rustfmt", "--edition", "2024", str(OUT)], check=True)
print(OUT)
